cybersecurityproject/cybersecurityproject/urls.py
from django.urls import path, include
from django.contrib import admin
from django.shortcuts import redirect

urlpatterns = [
    path('', lambda req: redirect('/polls/')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

cybersecurityproject/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('addpoll/', views.add_poll, name='add_poll')
]

cybersecurityproject/polls/models.py
from django.db import models
import datetime
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

cybersecurityproject/polls/forms.py
from django import forms
from . import models
from django.contrib.auth.forms import UserCreationForm, UserModel
from django.contrib.auth import password_validation
from django.forms import inlineformset_factory

class UserRegistrationForm(UserCreationForm):
    email = None
    password = None

    class Meta:
        model = UserModel
        fields = ("username","password")

class AddPoll(forms.ModelForm):
    class Meta:
        model = models.Question
        fields = ['question_text','pub_date']

class AddChoice(forms.ModelForm):
    class Meta:
        model = models.Choice
        fields = ['choice_text']

QuestionMetaInlineFormset = inlineformset_factory(
    models.Question,
    models.Choice,
    form=AddChoice,
    extra=3,
    # max_num=5,
    # fk_name=None,
    # fields=None, exclude=None, can_order=False,
    # can_delete=True, max_num=None, formfield_callback=None,
    # widgets=None, validate_max=False, localized_fields=None,
    # labels=None, help_texts=None, error_messages=None,
    # min_num=None, validate_min=False, field_classes=None
)

cybersecurityproject/polls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.views import generic
from . import forms
from django.utils import timezone

#add logger for example to views.py
#import logger
#logger = logging.getLogger('pollsLogger')
#then we can print logs using the following line anywhere in our code to track anything that happens, for example the addition of polls and voting actions
#logger.debug("write log text here..")

from .models import Choice, Question

def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:10]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else: 
        selected_choice.votes+=1

        #Here the following code is vulnerable to SQL injection, the actual code is the fix i.e. using django models which sanitize data            
        #cursor = conn.cursor()
	    #command = """UPDATE Choice SET (vote) WHERE id=(id) VALUES (?,?) ;"""
        #data_tuple=(selected_choice.votes,id)
	    #cursor.execute(command,data_tuple)
	    #conn.commit()

        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

def add_poll(request):
    if request.method == 'POST':
        form = forms.AddPoll(request.POST)
        formset = forms.QuestionMetaInlineFormset(request.POST)
        if form.is_valid() and formset.is_valid():
            
            #Here the following code is vulnerable to SQL injection, the actual code is the fix i.e. using django models which sanitize data            
            #cursor = conn.cursor()
	        #command = """INSERT INTO Question (question_text,pub_date) VALUES (?,?);"""
	        #data_tuple=(question_text,pub_date)
	        #cursor.execute(command,data_tuple)
	        #conn.commit()

            curForm = form.save(commit=False)
            curForm.save()
            pollMetas = formset.save(commit=False)
            for meta in pollMetas:
                meta.question = curForm
                meta.save()
            return redirect('polls:index')
    else:
        form = forms.AddPoll(initial={'pub_date': timezone.now()})
        product_meta_formset=forms.QuestionMetaInlineFormset()
    return render(request, 'polls/add_poll.html', {'form':form, 'product_meta_formset': product_meta_formset})

cybersecurityproject/polls/templates/polls/add_poll.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

{% block content %}
<div class="mainbox">
    <h2>Create new poll:</h2>

    <form action="{% url 'polls:add_poll' %}" method="post">
    <!-- Below we need to have {% csrf_token %} -->
    {% csrf_token %}
    {{form}}
    <h5>Add Choices</h5>
        {{ product_meta_formset.non_form_errors }}
        {{ product_meta_formset.management_form }}
        {% for form in product_meta_formset %}
        <div class="labelText">
            <div class="labelText">{{form.choice_text.label}}: {{ form.choice_text }}</div>
        </div>
        {% endfor %}
    <input type="submit" value="Add poll">
    </form>
</div>
{% endblock %}

cybersecurityproject/polls/templates/polls/detail.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

<div class="mainbox">
    <h1>{{ question.question_text }}</h1>

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <form action="{% url 'polls:vote' question.id %}" method="post">
        <!-- Below we need to have {% csrf_token %} -->
        {% csrf_token %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
        <input type="submit" value="Vote">
    </form>
</div>

cybersecurityproject/polls/templates/polls/index.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

<div class="mainbox">
    <h1>Current Polls</h1>
    {% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}

    <a href="{% url 'polls:add_poll' %}">Create new poll</a>
</div>

cybersecurityproject/polls/templates/polls/results.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

<div class="mainbox">
    <h1>{{ question.question_text }}</h1>

    <ul>
    {% for choice in question.choice_set.all %}
        <li>[{{ choice.votes }}] vote{{ choice.votes|pluralize }}  -  {{ choice.choice_text }}</li>
    {% endfor %}
    </ul>

    <a href="{% url 'polls:index' %}">Vote on another poll?</a>
</div>